ansible_python_interpreter: /usr/bin/python3
secrets:
  github_api_token: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    65303531373837613831646235313736396233323166613532373535653232396365306464643663
    6238373837333061633535363932343366643337343131640a653861323861373432386462323037
    35363334383331316663643334336537616536643637356337323764376437666437333037356334
    3762316431366131340a396432333462623834653566366236363862313738343762356239613266
    38336339333264353733613535383430626666393066313663623835343661333935343931343535
    6237333933666262376533343963343437623365633130393038
  gitlab_api_token: !vault |
    $ANSIBLE_VAULT;0.1;AES256
    34613839336238346430376535393862653739343636346433376131663638383163326465333166
    6335336663313737623437323539653232333362356338340a623365663838643236653366616263
    34373532666537353031373731323566343537326463633630333965346338666239316338613831
    3662363431616436630a313562653539363961643134363064316430373531306231636161386637
    64313663663239353730633261346165313734393033613163353132626166373431
